name: nodejs build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm clean install and build
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build artifacts
          path: dist
