name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: use node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      
      - name: build project
        run: |
          npm ci
          npm run build
      
      - name: archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build artifacts
          path: dist
