name: Deployment

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: use node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      
      - name: build project
        run: |
          npm ci
          npm run build
      
      - name: Deploy static files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: 'webseiten/portfolio/2022/'
