name: Deployment

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: use node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      
      - name: build project
        run: |
          npm ci
          npm run build
      
      - name: Install lftp
        run: |
          sudo apt-get update -qy
          sudo apt-get install -y lftp

      - name: Deploy static files
        run: |
          lftp -e "set ssl:verify-certificate no; open ${{ secrets.FTP_HOST }}; user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }}; mirror --reverse --verbose --delete $LOCAL_DIR $SERVER_DIR; bye"
        env:
          LOCAL_DIR: dist/
          SERVER_DIR: /webseiten/portfolio/2022/
